# Welcome to Jekyll!

# Website settings
title: "SG"
description: "Saurabh's blog,use Jekyll and github pages."
keywords: "Saurabh,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://saurabh1e.github.io"
#url: "http://127.0.0.1:4000"

# author
author:
  name: 'Saurabh'
  first_name: 'Saurabh'
  last_name: 'Gupta'
  email: 'saurabh.1e1@gmail.com'
  facebook_username: 'saurabhg1e'
  github_username: 'saurabh1e'
  avatar: 'static/img/landing/saurabh.jpg'
  desc: "As a full stack web developer I love the web and how it can help people.
  I enjoy everything from architecture designing,  back-end development, to front-end development and deployment.
  My goal and motivation is to help people take advantage of the web, while learning and having fun."


# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: SG
  public_key: kYijEF1CMjYvaZDrvg7EF6ZaUWD5sQKckuuYb2vnSMfQJti7ATn7lmimPUIn6wlZ

# share
bshare:
#  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
#  id: UA-73784599-1

# growingIO
gio:
#  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: redcarpet
redcarpet:
  input: GFM
  syntax_highlighter: rouge
