# Welcome to Jekyll!

# Website settings
title: "Resume"
description: "Saurabh's blog,use Jekyll and github pages."
keywords: "Saurabh,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
#url: "http://www.jack003.com"
url: "http://127.0.0.1:4000"

# author
author:
  name: 'Saurabh'
  first_name: 'Saurabh'
  last_name: 'Gupta'
  email: 'saurabh.1e1@gmail.com'
  facebook_username: 'saurabhg1e'
  github_username: 'saurabh1e'
  avatar: 'static/img/landing/saurabh.jpg'
  desc: "As a full stack web developer I love the web and how it can help people. I enjoy everything from architecture designing,  back-end development, to front-end development and hosting.

         I always strive to find solutions rather than forcing certain techniques on to the problem. Every line of code introduce new potential bugs and increase the cost of development and maintenance.
         Therefore code should be seen as a necessary evil. If it's possible to solve the problem partly with existing products or libraries that is often the best solution.

         My goal and motivation is to help people take advantage of the web, while learning and having fun."


# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
